language: node_js
node_js:
  - '12'

os:
  - linux

cache:
  yarn: true
  directories:
    - lib
    - coverage
    - node_modules

env:
  matrix:
  - YARN_GPG=no

matrix:
  fast_finish: true
  allow_failures:
    - os: windows

script:
  - yarn build
  - yarn test --coverage
  - bin/run -v
  - yarn test:codecov:upload
  - bin/run . --fail=high

jobs:
  include:
  - stage: code style
    if: branch = master
    scripts:
      - yarn lint
      - yarn codecov
  - stage: runtime test
    if: branch = master
    scripts:
      - bin/run -v
      - bin/run https://github.com/DXHeroes/dx-scanner
      - bin/run https://github.com/moment/luxon
      - bin/run https://github.com/intoli/remote-browser
      - bin/run
    os: windows
  - os: linux
  - stage: release
    node_js: lts/*
    script: skip
    deploy:
      provider: script
      email: dev@dxheroes.io
      skip_cleanup: true
      script:
        - npx semantic-release
